### ISSUE TITLE
[Instant wallet] Liquid tx isn't showing in Transaction list on Home

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#289] opened 2024-05-10 18:10 UTC
Description : Unable to see Transaction tx received from liquid wallet in Transaction list in home
Error logs :  Unable to sync liquid wallet

**Comment by BullishNode** [comment] 2024-05-11 02:35
Very vague can you elaborate?

**Comment by yshwanth** [comment] 2024-05-11 13:37
This issue happened once but I can't recreate this isuue.

**Comment by i5hi** [comment] 2024-05-12 07:41
Maybe your network connection or you were on an old version and did not run `flutter packages upgrade` - run this by default everytime you pull from main.

Patches happening every few days in `lwk-dart` and `boltz-dart`

**Comment by i5hi** [comment] 2024-05-12 07:41
Please close the issue if the problem is resolved.

**Closed** 2024-05-13 08:47 UTC
